theme = "solarized-dark"
icons = "awesome"


[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block= "net"
format= "{signal_strength} {speed_down;M*B} {speed_up;M*B}"

[[block]]
block = "music"
player = "spotify"
max_width = 20
buttons = ["play", "next"]

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "memory"
display_type = "memory"
clickable = false
format_mem = "{mem_used_percents} {mem_used} /{mem_total}"
interval = 10
warning_mem = 75
critical_mem = 90

[[block]]
block = "temperature"
collapsed = false

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "4C:87:5D:A3:AC:5B"
format = "Bose"
format_unavailable = "Bose"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"

