---
- name: Install Kubernetes Dependencies
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
    state: present


- name: Download Google Kube GPG key
  become: true
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    executable: /bin/bash



- name: Set Up Repository
  become: true
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash

- name: Apt Update
  become: true
  apt:
    update_cache: yes

- name: Install Kubectl
  become: true
  apt:
    name:
      - kubectl
      - kubeadm
      - kubelet
    state: present

- name: Hold kubeadm
  become: true
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubelet
  become: true
  dpkg_selections:
    name: kubelet
    selection: hold

