all:
  hosts:
  children:
    servers:
      hosts:
        localhost:
        avery-seacow:
        avery-lion:
        avery-leopard:
        avery-salmon:
        avery-trout:
        avery-tuna:
        avery-orca:
