---
- name: Setup a new machine
  hosts: avery-seacow
  remote_user: avery

  tasks:
  # - name: Install Dependencies
  #   include_role:
  #     name: install_apt

  # - name: Install Python3
  #   include_role:
  #     name: install_python3

  # - name: Install Kitty
  #   include_role:
  #     name: install_kitty

  # - name: Install ZSH
  #   include_role:
  #     name: install_zsh

  # - name: Install Tmux
  #   include_role:
  #     name: install_tmux

  # - name: Install Emacs
  #   include_role:
  #     name: install_emacs

  - name: Install Docker
    include_role:
      name: install_docker
