- name: Change default shell for specified user
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh


- name: Download OhMyZSH
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/omz_installer.sh
    mode: '0755'

- name: Execute OMZ Installer
  shell: sh /tmp/omz_installer.sh
  args:
    executable: /bin/bash
  ignore_errors: true
  async: 30
  poll: 3


- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"


- name: Install zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Copy ZSH rc
  copy:
    src: files/.zshrc
    dest: "~/.zshrc"

