---
- name: Install Kubernetes Dependencies
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
    state: present


- name: Download Google GPG key
  become: true
  shell: |
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  args:
    executable: /bin/bash



- name: Set Up Repository
  become: true
  shell: |
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash

- name: Apt Update
  become: true
  apt:
    update_cache: yes

- name: Install Kubectl
  become: true
  apt:
    name:
      - kubectl
    state: present
