---
- name: Install Spotify
  become: true
  shell: |
    curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
    echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
  args:
    executable: /bin/bash

- name: Apt Update
  become: true
  apt:
    update_cache: yes

- name: Install Spotify
  become: true
  apt:
    name:
      - spotify-client
    state: present
