# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp9s0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
    enp7s0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 101
