[icons]
icons = "awesome5"

[theme]
theme = "solarized-dark"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:50) |"
short = " $title.str(max_w:30) |"

[[block]]
block= "net"
format= " $icon ^icon_net_down $speed_down.eng(prefix:M,w:3) ^icon_net_up $speed_up.eng(prefix:M,w:3) "

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:25,rot_interval:0.5) $play |}"

[[block]]
block = "docker"
interval = 20
format = " $icon $running/$total "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M)/$mem_total.eng(prefix:M)($mem_used_percents.eng(w:2)) "
format_alt = " $icon $mem_used_percents.eng(w:2) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "temperature"
format = " $icon $min min, $max max, $average avg "
format_alt = " $icon $max max "
interval = 2

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization $frequency.eng(w:4) "
format_alt = " $icon $frequency.eng(w:4) "

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon GPU $utilization $temperature $clocks"

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"
minimum = 0
cycle = [ 0, 30, 60, 100 ]

[[block]]
block = "battery"
format = " $icon $percentage $time "
full_format = " $icon $percentage "

[[block]]
block = "bluetooth"
mac = "4C:87:5D:A3:AC:5B"
format = " $icon "

[[block]]
block = "time"
interval = 60

