---
- name: Install fonts
  become: true
  shell: |
    mkdir -p ~/.fonts/adobe-fonts/source-code-pro
    git clone https://github.com/adobe-fonts/source-code-pro.git ~/.fonts/adobe-fonts/source-code-pro
    find ~/.fonts/ -iname '*.ttf' -exec echo \{\} \;
    fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro
  args:
    executable: /bin/bash
